### ISSUE TITLE
Good project

### ISSUE THREAD

**Issue by spiritfox358** [zclzone/vue-naive-admin#1]
This project is too simple, too naive. Why don't you use typescript to develop projects

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/32157422/154266962-d345c3de-133c-4c56-b64b-c6ab76209cd5.png">

**Comment by zclzone** [comment]
Thank you for your advice. This is a template for small and medium-sized projects or personal projects, for small and medium-sized projects and personal projects, 
I thins TS is not a wise choice, Use JS will have a more comfortable experience and more efficient development. In addition, many people dislike TS, Of course, I also plan to create a TS version, Let everyone choose JS or TS.
