### ISSUE TITLE
mock 环境接口报错问题

### ISSUE THREAD

**Issue by leipu247** [zclzone/vue-naive-admin#102]
mock 环境下，https://mock.apipark.cn/m1/3776410-0-default/permission/button/4 报错404 ，望核查

**Comment by zclzone** [comment]
mock 环境没有这个接口，我抽空补一下

**Comment by zclzone** [comment]
mock接口已补充 https://apifox.com/apidoc/shared-ff4a4d32-c0d1-4caf-b0ee-6abc130f734a/api-234699449
