### ISSUE TITLE
pinia持久化问题

### ISSUE THREAD

**Issue by 15289450519** [zclzone/vue-naive-admin#107]
pinia持久化中设置paths数组无效，开启持久化会将所有参数持久化
![image](https://github.com/user-attachments/assets/8fc89e18-bab9-47af-ad2e-12eb097f988f)
这个hasOk应该在刷新页面的时候重置为false，但是并没有

**Comment by zclzone** [comment]
paths 改成 pick, https://github.com/zclzone/vue-naive-admin/commit/9b510e8350daf07d00ebc1f4ebaf049a29d790a4

**Comment by 15289450519** [comment]
> paths 改成 pick, [9b510e8](https://github.com/zclzone/vue-naive-admin/commit/9b510e8350daf07d00ebc1f4ebaf049a29d790a4)

👍🏻搞定，
