### ISSUE TITLE
unocss部分不生效问题

### ISSUE THREAD

**Issue by 15289450519** [zclzone/vue-naive-admin#109]
![微信截图_20241218113901](https://github.com/user-attachments/assets/22bb1155-65d2-44ae-9079-4bcc2db7bee9)

**Comment by xiaofuyesnew** [comment]
类名的书写一般不带空格，可以写成 `max-h-[calc(100vh-200px)]`。

**Comment by zclzone** [comment]
> 类名的书写一般不带空格，可以写成 `max-h-[calc(100vh-200px)]`。

@15289450519 正解

**Comment by 15289450519** [comment]
> 类名的书写一般不带空格，可以写成 `max-h-[calc(100vh-200px)]`。

谢谢

**Comment by 15289450519** [comment]
> > 类名的书写一般不带空格，可以写成 `max-h-[calc(100vh-200px)]`。
> 
> @15289450519 正解

谢谢
