### ISSUE TITLE
开发环境报vue找不到

### ISSUE THREAD

**Issue by ChenshouLiang** [zclzone/vue-naive-admin#12]
[vite] error while updating dependencies:
Error: Build failed with 3 errors:
node_modules/vue-demi/lib/index.mjs:1:21: ERROR: [plugin: vite:dep-pre-bundle] Detected inconsistent metadata for the path "node_modules/vue/dist/vue.runtime.esm-bundler.js" when it was imported here:
node_modules/vue-demi/lib/index.mjs:27:14: ERROR: [plugin: vite:dep-pre-bundle] Detected inconsistent metadata for the path "node_modules/vue/dist/vue.runtime.esm-bundler.js" when it was imported here:
node_modules/vue-router/dist/vue-router.esm-bundler.js:6:187: ERROR: [plugin: vite:dep-pre-bundle] Detected inconsistent metadata for the path "node_modules/vue/dist/vue.runtime.esm-bundler.js" when it was imported here:

**Comment by zclzone** [comment]
依赖安装成功了吗，推荐使用pnpm安装
