### ISSUE TITLE
首次打开页面有Vue Router警告

### ISSUE THREAD

**Issue by linjiacheng** [zclzone/vue-naive-admin#24]
[Vue Router warn]: No match found for location with path ...

调用app.use(router)时，异步路由包括根路径还未加入到router中

**Comment by zclzone** [comment]
这是vue-router对动态添加路由的警告，给vue-router提过issue，但官方并不打算修复这个问题。

现在暂时没有比较好的方案避免这个警告，但是不影响使用，以后有好的方案会尝试修复，或者你有什么好的方案也可以帮忙提PR，谢谢
