### ISSUE TITLE
Critical dependency: Accessing import.meta directly is unsupported (only property access is supported)

### ISSUE THREAD

**Issue by 0001Robert** [zclzone/vue-naive-admin#28]
hello, first thank you for providing this amazing admin on naive
i tried to integrate this template in symfony using [webpack encore](https://github.com/symfony/webpack-encore)

but when bundling the application this is what i get:
```
1 warn  in ./assets/admin/src/router/routes/index.js

Critical dependency: Accessing import.meta directly is unsupported (only property access is supported)
```

it pointed here:
```js
// src/router/routes/index.js
const modules = import.meta.glob('@/views/**/route.js', { eager: true })
```

is there something that i need to enable in webpack to resolve this issue or is there another alternative to it ?
from my basic understanding this will load all the `route.js` inside the `views` folder
thanks..

**Comment by zclzone** [comment]
maybe you can manually collect all the routes instead of using vite's glob feature.

**Comment by 0001Robert** [comment]
ohh i have to try it manually i have not thought about it, i have been looking into `require.context` and try different things but non of them worked

**Comment by 0001Robert** [comment]
thank you so much it worked manually <3
