### ISSUE TITLE
前端已进入无需引入直接用的时代了，建议改进

### ISSUE THREAD

**Issue by Baiyuetribe** [zclzone/vue-naive-admin#3]
可以去看看antfu大佬提供的解决方案
组件自动引入：`[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)`
API自动引入：`[unplugin-auto-import](https://github.com/antfu/unplugin-auto-import)`
还有一个是路由页面自动引入，你自己找找看。
或者参考现成案例的`https://github.com/dishait/tov-template`

以上都是来源于Nuxt3的设计逻辑，antfu是Vue和Nuxt3的核心开发者，所以以上设计非要有意思

**Comment by zclzone** [comment]
大概了解这些方案，一直在观望，近期会安排试坑集成，多谢提醒

**Comment by zclzone** [comment]
> 可以去看看antfu大佬提供的解决方案 组件自动引入：`[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)` API自动引入：`[unplugin-auto-import](https://github.com/antfu/unplugin-auto-import)` 还有一个是路由页面自动引入，你自己找找看。 或者参考现成案例的`https://github.com/dishait/tov-template`
> 
> 以上都是来源于Nuxt3的设计逻辑，antfu是Vue和Nuxt3的核心开发者，所以以上设计非要有意思

unplugin-vue-components已经集成，至于unplugin-auto-import，在js版本暂不打算集成，我是这样考虑的，因为vscode编辑器基本都可以自动import，使用unplugin-auto-import反而会导致依赖方与被依赖方的相关性不易察觉，面对不熟悉的代码，会很难定位

**Comment by Baiyuetribe** [comment]
unplugin-auto-import不是引入所有的，目前支持的仅有常用的，比如vue、vue-route、pina等。页面路由自动注册应该是比较先进的，建议优先考虑
