### ISSUE TITLE
Xss漏洞

### ISSUE THREAD

**Issue by Mia0a-hi** [zclzone/vue-naive-admin#30]
![image](https://user-images.githubusercontent.com/40627909/203245953-62e87400-3f9f-44c9-b112-05c6f7cf04aa.png)

payload:<a href="javascript&#x3ax=1;alert(1)">Click

**Comment by Mia0a-hi** [comment]
```
<a href="javascript&#x3ax=1;alert(1)">Click

**Comment by zclzone** [comment]
这个是依赖库 md-editor-v3 的bug，可以去这个 [仓库](https://github.com/imzbf/md-editor-v3) 提 issue

**Comment by zclzone** [comment]
> ```
> <a href="javascript&#x3ax=1;alert(1)">Click
> ```

这个是依赖库 md-editor-v3 的bug，可以去这个 [仓库](https://github.com/imzbf/md-editor-v3) 提 issue
