### ISSUE TITLE
表单中的输入框，输入下划线显示为空白

### ISSUE THREAD

**Issue by w2tbp** [zclzone/vue-naive-admin#36]
![image](https://github.com/zclzone/vue-naive-admin/assets/26455015/168f7b83-c36f-4d90-9c81-9903500d4349)

如果将 font-size 改大一点就能显示了

ts版本的倒是能显示

**Comment by zclzone** [comment]
naive ui的bug？我这没有复现

**Comment by w2tbp** [comment]
不知道咋回事，我刚试了试也不能复现了
