### ISSUE TITLE
关于naive ui表格的使用

### ISSUE THREAD

**Issue by CS-liujf** [zclzone/vue-naive-admin#37]
你好，naive ui的表格需要依靠h函数才能完成单元格内的渲染，比如
https://github.com/zclzone/vue-naive-admin/blob/5aa4d3d5aedfc04d42171a05a651249c41899434/src/views/demo/table/index.vue#LL119C4-L127C7

请问有什么封装的方法可以做到直接在template标签里通过slot来写单元格内的组件吗？

**Comment by zclzone** [comment]
naive ui官方没有这样的插槽，靠业务代码封装去实现不太现实，如果非要这样写可以推荐使用element plus
