### ISSUE TITLE
路由白名单

### ISSUE THREAD

**Issue by remember-5** [zclzone/vue-naive-admin#38]
可以考虑出一个路由白名单吗？因为在业务中，有部分页面是无需认证即可访问

**Comment by remember-5** [comment]
> 可以考虑出一个路由白名单吗？因为在业务中，有部分页面是无需认证即可访问

已经找到问题 `src/router/guard/permission-guard.js:3`

**Comment by leriocn** [comment]
[已提Issue，](https://github.com/zclzone/vue-naive-admin/issues/53)
白名单最好能直接复用Router中的Meta，如增加一个meta属性 nologin=true
避免写死具体路径或者routername。支持分散位置放置router。
Thanks Contributer
