### ISSUE TITLE
请教一下这里的写法和作用

### ISSUE THREAD

**Issue by zhanglolo** [zclzone/vue-naive-admin#4]
https://github.com/zclzone/vue-naive-admin/blob/402c7db7babf0dc90e1a3a4fd3ca8c43784bba20/src/App.vue#L7-L14

虽然看代码意思应该是根据路由上的元信息来判断这个页面是否被`keep-alive`，但是完全看不明白在`<router-view></router-view>`中写上`<template></template>`是什么意思，还用上了`slot`。
我自己尝试模仿着写，最后也没实现。

提了个奇怪的问题，希望可以得到解答。🙏

**Comment by zclzone** [comment]
router-view的相关写法请参考vue-router的[文档](https://router.vuejs.org/zh/api/#router-view-%E7%9A%84-v-slot)
至于keep-alive不生效问题确实是存在，我已经修复了，并添加了测试keep-alive的页面，请拉取最新代码，或者在我新添加的[页面](https://template.qszone.com/test/keep-alive)进行体验
感谢关注和体验，有任何问题可以随时Issue或者也可以创建request一起参与开源

**Comment by zhanglolo** [comment]
非常感谢解答，继续学习。
