### ISSUE TITLE
关于src/router/guard/permission-guard.js文件中if (WHITE_LIST.includes(to.path)) return true判断问题

### ISSUE THREAD

**Issue by amplest** [zclzone/vue-naive-admin#44]
实际场景
1. 用户正常登录后获取到权限及动态路由并能完整展示
2. 页面停留在任意页面（不要首页）然后手动修改token，使其过期形成登录过期现象
3. 刷新页面
4. 经过resolveResError方法走useUserStore().logout()的时候会直接跳转到404

**Comment by zclzone** [comment]
没有复现，useUserStore().logout()是清除登录状态然后跳转登录页
