### ISSUE TITLE
您的Logo和Last.fm的Logo是不是相差无几

### ISSUE THREAD

**Issue by nicopcat** [zclzone/vue-naive-admin#46]
开源不易，尊重作者的辛苦。
也许logo可以找朋友或者点点点小钱甚至自己用ps/procreate设计一下，也能突出个人的风格。

诚心建议，非找茬。

**Comment by zclzone** [comment]
> 开源不易，尊重作者的辛苦。 也许logo可以找朋友或者点点点小钱甚至自己用ps/procreate设计一下，也能突出个人的风格。
> 
> 诚心建议，非找茬。

看了一下确实有很像，但在你说之前我根本都不知道有这个网站，我是从开源图标库里找的，对应的是我qszone这个域名

当然也有可能是这个图标库参考lastfm设计的，然后就撞车了

总之，感谢提醒，刚好最近新买了一个域名，logo也会更新
