### ISSUE TITLE
请问在项目中如何配置jsx的eslint检查啊

### ISSUE THREAD

**Issue by weblowb** [zclzone/vue-naive-admin#47]
![image](https://github.com/zclzone/vue-naive-admin/assets/19431970/20ce14d0-0951-4824-bd4c-be3706fd7025)
![image](https://github.com/zclzone/vue-naive-admin/assets/19431970/e104114a-d52f-4547-9d56-4c31605fe389)
![image](https://github.com/zclzone/vue-naive-admin/assets/19431970/ffd77572-b174-4362-b740-7790eb00cc2b)

**Comment by qingmang** [comment]
@weblowb 怎么配置的 我也是这个问题
![image](https://github.com/zclzone/vue-naive-admin/assets/67047984/fcf10d37-f3f5-47ac-8eef-858fe3080d94)
![image](https://github.com/zclzone/vue-naive-admin/assets/67047984/6364e030-d928-4970-818f-164459c2088f)

**Comment by zclzone** [comment]
@qingmang @weblowb 有问题可以进群讨论
