### ISSUE TITLE
Thanks Contributors，建议增加配置支持默认主题色。

### ISSUE THREAD

**Issue by leriocn** [zclzone/vue-naive-admin#52]
建议通过env支持默认 白色或者黑色主题，以及是否允许换主题的配置项，感谢无私奉献。

**Comment by zclzone** [comment]
settings/theme.json 有提供主题色的配置，默认light或者dark目前未做配置，后续可能提供，欢迎提PR

**Comment by zclzone** [comment]
> 建议通过env支持默认 白色或者黑色主题，以及是否允许换主题的配置项，感谢无私奉献。

useDark默认是自动模式，会根据浏览器的深浅色模式自动调整，手动设置默认值有点画蛇添足，所以是否dark模式不提供默认配置
