### ISSUE TITLE
Thanks Contributer，若后端token跟前端的token验证方式不同，如后台修改用户ID发生变化，导致Token鉴权更改会出无法使用问题。

### ISSUE THREAD

**Issue by leriocn** [zclzone/vue-naive-admin#54]
如题，如果已经缓存在前端Locastorage，但是后端修改了用户ID，这个时候鉴权接口会报错403，但是403的接口会导致前端空白，除非删除前端token缓存，否则一直无法打开。

**Comment by zclzone** [comment]
这些业务上的细节其实很难考虑全，只能是对接真实接口的针对性的修改，比如使用过程中某个接口报403是不会白屏的，并且会给出对应的错误提示，刷新页面的时候获取用户信息接口403就有可能会白屏，针对这点倒是可以优化一下，我有空看下，或者你有什么想法也可以提交PR

**Comment by xiaohuasi** [comment]
自己解决呀，基础公开的框架不能乱改的。你的需求是业务上的需求，不是普遍的需求，自己做业务开发吧。

**Comment by xiaohuasi** [comment]
你可以在403里面去更新token，刷新页面
