### ISSUE TITLE
弹窗保存时，表单校验未通过，没有提示，而是直接关闭

### ISSUE THREAD

**Issue by MYyes-pp** [zclzone/vue-naive-admin#59]
ResAddOrEdit.vue中的onSave函数校验未通过，直接return 会直接关闭，应该为return false。

**Comment by zclzone** [comment]
> ResAddOrEdit.vue中的onSave函数校验未通过，直接return 会直接关闭，应该为return false。

 之前改了未改全，现已改成表单校验不捕获错误了，校验报错会直接阻止往下执行

#https://github.com/zclzone/vue-naive-admin/commit/144845073a295e8c0d35043a8d082cfe05ae0771
