### ISSUE TITLE
用户管理页面，handleOpen参数传递错误，导致打开modal点击确定没反应

### ISSUE THREAD

**Issue by MYyes-pp** [zclzone/vue-naive-admin#60]
2.0里面用户管理的分配角色，重置密码，使用handleopen时传错参数，导致点击确定没有反应。  直接传的onSave  改为onOk:onSave,

**Comment by zclzone** [comment]
> 2.0里面用户管理的分配角色，重置密码，使用handleopen时传错参数，导致点击确定没有反应。 直接传的onSave 改为onOk:onSave,

已修复，#https://github.com/zclzone/vue-naive-admin/commit/944de898aaed8cb73ed85feebbb4ecba11c159c2
