### ISSUE TITLE
低版本浏览器访问报错：Uncaught SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by xuhongv** [zclzone/vue-naive-admin#64]
低版本浏览器访问报错：Uncaught SyntaxError: Unexpected token ?

![image](https://github.com/zclzone/vue-naive-admin/assets/25237870/2d0d7ebd-0e59-4ff9-8d52-fb54e8c5430f)

**Comment by zclzone** [comment]
版本有多低？旧版本浏览器确实会有不兼容的情况，但只要不是太旧肯定是没问题的
