### ISSUE TITLE
在App.vue中为什么没定义 markRaw 和  defineAsyncComponent 也可以用

### ISSUE THREAD

**Issue by alexnest** [zclzone/vue-naive-admin#65]
请教个问题：在App.vue中为什么没定义 markRaw 和  defineAsyncComponent 也可以用这两个方法、

**Comment by zclzone** [comment]
> 请教个问题：在App.vue中为什么没定义 markRaw 和 defineAsyncComponent 也可以用这两个方法、

有unplugin插件自动导入

我有建交流群，有疑问可以加群提问
