### ISSUE TITLE
有没有详细的文档

### ISSUE THREAD

**Issue by aclstack** [zclzone/vue-naive-admin#71]
新手小白想用这个，但是完全不知道后端需要返回什么，比如我想自定义返回格式，完全不知道改哪

**Comment by aclstack** [comment]
再比如token那块，我返回的事token，而我看代码里好像用的是accesstoken，但是改了几处页面显示登录成功，但是依旧无法跳转还是登录页面

**Comment by aclstack** [comment]
然后当初用vue-element-admin感觉完全没有这个这么复杂

**Comment by zclzone** [comment]
@aclstack 顺着接口找就知道要改哪里，如果返回的结构是一样的，改动这里就行了

![image](https://github.com/zclzone/vue-naive-admin/assets/49337591/c09d6cae-439e-433d-bad4-28c36e08aee2)

**Comment by zclzone** [comment]
> 然后当初用vue-element-admin感觉完全没有这个这么复杂

肯定会更复杂一点的，毕竟 vue-element-admin 只是纯前端，虽然它算是 vue后台管理的鼻祖，但在前端技术的不断更迭下，它对工程化和工具化的应用明显已经落后很多了

**Comment by zclzone** [comment]
有疑问可以加群讨论
