### ISSUE TITLE
二次登录后标签页会多出登录标签

### ISSUE THREAD

**Issue by pangonglong** [zclzone/vue-naive-admin#8]
![微信截图_20220413145832](https://user-images.githubusercontent.com/19756236/163118645-be74efec-7ee2-4a7a-8f18-413da7854a0f.png)

**Comment by zclzone** [comment]
已经修复，详见 [commit 094a9dc](https://github.com/zclzone/vue-naive-admin/commit/094a9dcb3b2a797f2179631ed7a3d8df59824092)
