### ISSUE TITLE
^^^^^^^^

### ISSUE THREAD

**Issue by zlecheng** [zclzone/vue-naive-admin#83]

**Comment by zclzone** [comment]
你的问题本身不是项目问题，自己基础问题不去学习不去用搜索引擎，别人都回答你了，还有脸提issue说群里不回答问题，点个star地球都得围着你转了？三个群五六百号人你是头一个，我的项目配不上你，自己退吧

**Comment by zclzone** [comment]
@zlecheng 喜欢提issue，给你置顶了

**Comment by zlecheng** [comment]
> @zlecheng 喜欢提issue，给你置顶了

怎的，刚学编程还没有提问题的权利了？……

**Comment by zclzone** [comment]
@zlecheng 可以提啊，人家也回答你了，你自己看不懂别人回答的东西是不是应该自己去学习去补基础，人家也没收你钱凭什么要回答你问题，况且太基础的东西别人本来就不乐意回答，人家回答你了不说声谢谢，还跑这里来阴阳说不回答问题

另外，刚学编程不应该成为你理直气壮和理所当然的底气

**Comment by zlecheng** [comment]
> @zlecheng 可以提啊，人家也回答你了，你自己看不懂别人回答的东西是不是应该自己去学习去补基础，人家也没收你钱凭什么要回答你问题，况且太基础的东西别人本来就不乐意回答，人家回答你了不说声谢谢，还跑这里来阴阳说不回答问题
> 
> 另外，刚学编程不应该成为你理直气壮和理所当然的底气

你是看不到群里的  谢谢 两个字 ？行吧，无所谓，只能怪自己太垃圾了，
