### ISSUE TITLE
项目编译报错"statSync" is not exported by "__vite-browser-external"

### ISSUE THREAD

**Issue by AdamvvYau** [zclzone/vue-naive-admin#85]
请教：项目编译报错"statSync" is not exported by "__vite-browser-external"，有人遇到同样的错误吗，
![微信截图_20240702154812](https://github.com/zclzone/vue-naive-admin/assets/26832099/18fc2a61-b17f-4456-b2c2-5e0e718f9403)
该如何解决？

**Comment by zclzone** [comment]
node版本是多少，依赖安装成功了吗

**Comment by AdamvvYau** [comment]
import { e } from 'unocss'
多了一行引用，删除了就OK了。
