### ISSUE TITLE
建议id和错误码都改成字符串

### ISSUE THREAD

**Issue by AllenDengMs** [zclzone/vue-naive-admin#89]
在中小项目中，所有表的id主键都统一使用long类型。后台如果直接将long类型返回给前端，js会丢精度，后3位会自动变成0导致id出错。然后后台都是统一将long类型转成字符串返回给前端的。

另外，小项目，错误码用纯数字类型，后台管理起来非常烦。对接很多三方的接口，他们的错误码也是没有统一标准的，有的是数字，有的是纯字符串，包括阿里系的也看见有用纯英文字符串的。小项目，直接用code: "token.expired"这种更具直观。

虽然我自己改改也很快。现在正在重写一版，代码结构简单而且能上生产环境Java后台和go后台，并开源出来。java版我已经写好了。如果我改了前端代码，和你的开源的项目就接不上了。希望能支持以一下id和code使用字符串类型。

**Comment by zclzone** [comment]
1. 自增主键丢精度本身就是一个伪命题，js整数最大精度值是9007199254740992（约900兆），
什么业务会有这么多条数据？假设有这么多条数据，那么什么数据库能支撑这么庞大的数据量，mysql数据超2000w行性能就会明显下降，阿里也提出单表超过500w行推荐分库分表
2. 正如你说的，错误码没有统一标准，你用得多的是字符串，而我见过的绝大多数都是数字，我觉得这两种都没毛病，前后端约定好就行了
3. 这点没有办法，适配了你的，别人已对接的就对不上了，建议你开源的使用数字，自己业务改成字符串

**Comment by AllenDengMs** [comment]
好的，开源版已经按你源码的标准设计了，错误码确实是数字类型的比较多。id那个还是非常必要做字符串的，订单表、支付流水表，因为支付流程问题，需要先生成id后插入数据，通常会使用雪花id，雪花id会丢精度的。后台框架为了统一，实体均继承同一个基础类，也就是所有表通用同一个主键类型，为了兼容雪花id，所有字段都是使用long类型的。

**Comment by AllenDengMs** [comment]
开源版用的人多了确实存在新旧版本兼容性问题。我做两个版本吧。这个issue关闭了

**Comment by zclzone** [comment]
@AllenDengMs 表id没有限制的，数字或者字符串都可以

**Comment by AllenDengMs** [comment]
@zclzone 感谢提供前端项目！非常完美。
Java后台开源版做好了，按你定义好API的标准做的。直接启动就可以用。虽然readme也有提供java版，看了一遍，鉴权部分功能不完善，而且部分代码使用了个人代码库依赖，代码没法改，所以直接重做了一个。表结构也是基本用你提供的sql。正在录制后台视频讲解。
https://github.com/AllenDengMs/isme-java

**Comment by zclzone** [comment]
> @zclzone 感谢提供前端项目！非常完美。 Java后台开源版做好了，按你定义好API的标准做的。直接启动就可以用。虽然readme也有提供java版，看了一遍，鉴权部分功能不完善，而且部分代码使用了个人代码库依赖，代码没法改，所以直接重做了一个。表结构也是基本用你提供的sql。正在录制后台视频讲解。 https://github.com/AllenDengMs/isme-java

已将此项目推荐至项目文档及README中，感谢贡献。
