### ISSUE TITLE
手机分辨率下浏览需要改进

### ISSUE THREAD

**Issue by wanvb** [zclzone/vue-naive-admin#91]
手机分辨率下浏览就看不清楚表格的内容了，如果用来开发应用，某些特殊时候比如说对应的用户在高铁地铁上或者说在外面，必须要使用手机进行业务操作，就很不方便，请问是否能改善一下谢谢

**Comment by zclzone** [comment]
先加到计划清单，后面有空加上 https://github.com/zclzone/vue-naive-admin/issues/92#issue-2485154999
