### ISSUE TITLE
新建菜单中的组件路径是否可以添加搜索

### ISSUE THREAD

**Issue by zeng-alt** [zclzone/vue-naive-admin#99]
组件路径太多的情况的下难以查找
![屏幕截图 2024-10-15 094452](https://github.com/user-attachments/assets/4d385368-de74-4977-b618-8352be12ce87)
094452.png…]()

**Comment by 34892002** [comment]
哥，这个组件本来就可以搜索，你直接输入就能模糊匹配😂
